openapi: 3.0.2

info:
  title: API
  version: 0.0.1

servers:
  - url: http://localhost:7777
    description: Локальный моковый сервер
    
tags:
  - name: questions
    description: вопросы для теста

paths:
  /questions:
    get:
      tags:
        - questions
      summary: Возвращает массив вопросов для теста
      operationId: getQuestions
      responses:
        200:
          $ref: "#/components/responses/QuestionsResponse"

#  -------------------------------------------------------------------------------------------------------------------

components:
  responses:
    QuestionsResponse:
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/QuestionModel"

  schemas:
    QuestionModel:
      title: QuestionModel
      type: object
      description: Вопсрос для теста
      required:
        - id
        - question
        - isMulti
        - responses
      properties:
        id:
          type: integer
          format: int64
        question:
          type: string
        isMulti:
          type: boolean
          description: если true, то ожидаются несколько ответов, иначе ожидается один
        responses:
          type: array
          items:
            $ref: "#/components/schemas/QuestionResponseModel"
    QuestionResponseModel:
      title: QuestionResponseModel
      type: object
      description: Ответ на вопрос
      required:
        - id
        - content
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string