openapi: 3.0.2

info:
  title: API
  version: 0.0.1

servers:
  - url: http://localhost:7777
    description: Локальный моковый сервер
    
tags:
  - name: tests
    description: методы, возвращающие тесты

paths:
  /tests:
    get:
      tags:
        - tests
      summary: Возвращает массив тестов
      operationId: getTests
      parameters:
        - $ref: "#/components/parameters/length"
      responses:
        200:
          $ref: "#/components/responses/TestsResponse"

#  -------------------------------------------------------------------------------------------------------------------

components:
  responses:
    TestsResponse:
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/TestModel"

  schemas:
    TestModel:
      title: TestModel
      type: object
      description: Фильтр
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      example:
        id: 1
        name: первый тест

  parameters:
    length:
      name: length
      in: query
      description: количество тестов
      required: true
      schema:
        type: integer
