openapi: 3.0.2

info:
  title: API
  version: 0.0.1

servers:
  - url: http://localhost:7777
    description: Локальный моковый сервер
    
tags:
  - name: questions
    description: вопросы для теста

paths:
  /questions:
    get:
      tags:
        - questions
      responses:
        200:
          $ref: "#/components/responses/QuestionsResponse"
    post:
      tags:
        - questions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuestionsDto"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string

#  -------------------------------------------------------------------------------------------------------------------

components:
  responses:
    QuestionsResponse:
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/QuestionModel"

  schemas:
    QuestionsDto:
      title: QuestionsDto
      type: object
      required:
        - 'answers'
      properties:
        answers:
          type: array
          items:
            oneOf:
              - type: string
              - type: integer
              - type: array
                items:
                  type: integer

    QuestionsAnswerModel:
      title: QuestionsDto
      type: array
      items:
        $ref: "#/components/schemas/QuestionModel"
    QuestionModel:
      title: QuestionModel
      type: object
      description: Вопсрос для теста
      required:
        - id
        - question
        - type
      properties:
        id:
          type: integer
          format: int64
        question:
          type: string
          description: Текст вопроса
        type:
          type: string
          enum:
            - radio
            - checkbox
            - input
            - textarea
        answers:
          type: array
          items:
            $ref: "#/components/schemas/QuestionAnswerModel"
    QuestionAnswerModel:
      title: QuestionAnswerModel
      type: object
      description: Ответ на вопрос
      required:
        - id
        - content
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        type:
          type: string
          enum:
            - radio
            - checkbox
            - input
            - textarea